### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Update minimum Go version to match upstream coredns.
* Update Go modules.
* Remove unecessary inline vendoring.
* Update build/patches for latest Go version.
* Bump Go version in Dockerfile.
* Add `v4` to Go module definition to match tagged major version.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by cybertron** [comment]
/ok-to-test

I'm not sure what implications removing the vendoring would have, but we don't actually use this project anymore so if it passes ci I'm okay with it.

**Comment by SuperQ** [comment]
Removing vendoring is now basically automatically handled by Go modules. Everything that needs modules triggers a transparent `go mod download` which has the same validation as a vendor dir.

**Comment by SuperQ** [comment]
@cybertron Do you know what controls the Go version used in the pipeline? It seems to be pinned to Go 1.15, but I don't see that in any of the config files.

**Comment by cybertron** [comment]
It's managed in the release repo. I submitted an update to move the job images to be more current: https://github.com/openshift/release/pull/35796

**Comment by SuperQ** [comment]
I had to force enable `-mod=mod` in a couple places to ignore the `/vendor` dir. But looks like we're able to build now.

**Review by cybertron — APPROVED** [review]
/lgtm

**Comment by SuperQ** [comment]
Thanks! Would you mind adding a new git tag to release this?

**Comment by cybertron** [comment]
> Thanks! Would you mind adding a new git tag to release this?

Sorry for the delay. I've pushed a v4.13 tag, which corresponds to the OpenShift version where this landed, like our existing tags.

**Pull request merged**
